[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "miniml"
version = "1.0.0"
authors = [
  { name="Philipp O'Neill", email="philipp.oneill@physiologie.uni-freiburg.de" },
  { name="Igor Delvendahl", email="igor.delvendahl@physiologie.uni-freiburg.de" },
]
description = "A deep learning framework for synaptic event detection"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "scikit-learn==1.5.1",
    "matplotlib==3.6.3",
    "h5py==3.11.0",
    "numpy<2.0.0",
    "scipy==1.11.1",
    "tensorflow>=2.14.0,<2.16.0",
    "pyabf==2.3.8",
    "ruptures==1.1.10",
]

[project.optional-dependencies]
gui = [
    "PyQt5==5.15.11",
    "qt-material==2.14",
    "pyqtgraph==0.13.7",
]

[project.scripts]
miniml-gui = "miniml.miniML_gui:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["miniml*"]

[tool.setuptools.package-data]
miniml = ["icons/*.svg", "miniml.css.template", "minML_icon.png", "models/**/*.h5"]
