[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "miniml"
version = "1.1.0"
authors = [
  { name="Philipp O'Neill", email="philipp.oneill@physiologie.uni-freiburg.de" },
  { name="Martin Baccino Calace", email="martin.baccinocalace@uzh.ch" },
  { name="Igor Delvendahl", email="igor.delvendahl@physiologie.uni-freiburg.de" },
]
maintainers = [
  { name="Igor Delvendahl", email="igor.delvendahl@physiologie.uni-freiburg.de" },
]
description = "A deep learning framework for synaptic event detection"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.11,<3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "scikit-learn==1.5.2",
    "matplotlib==3.6.3",
    "h5py==3.11.0",
    "numpy<2.0.0",
    "scipy==1.11.4",
    "tensorflow>=2.14.0,<2.16.0",
    "pyabf==2.3.8",
    "ruptures==1.1.10",
]

[project.optional-dependencies]
gui = [
    "PyQt5==5.15.11",
    "qt-material==2.14",
    "pyqtgraph==0.13.7",
]

dev = ["ruff"]

[project.urls]
Homepage = "https://github.com/delvendahl/miniML"
Repository = "https://github.com/delvendahl/miniML"
Issues = "https://github.com/delvendahl/miniML/issues"
Documentation = "https://delvendahl.github.io/miniML"
Publication = "https://doi.org/10.7554/eLife.98485.3"

[project.gui-scripts]
miniml-gui = "miniml.gui.main:entry_point"

[tool.setuptools.package-data]
"miniml.resources" = ["**/*.*"]
