# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: miniML documentation
author: PS O'Neill & I Delvendahl
logo: images/logo.png
copyright: "2025"
exclude_patterns: [_build, .DS_Store, .pytest_cache, tests, "**.ipynb_checkpoints"] 
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto
  timeout: 1000

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/delvendahl/miniml-docs  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  favicon: "images/favicon.ico"
